// data
var data = [
{
    level:0,
    text:'示例管理',
    id:1,
    nodes:[
    {
        level:1,
        text:"示例-2层",
        id:11,
        nodes:[
        {
            level:1,
            text:"示例-3层1",
            id:12,
            nodes:[
            {
                level:1,
                text:"示例-4层1",
                id:12,
                nodes:[
                {
                    level:1,
                    text:"示例-5层1",
                    id:12,
                },
                {
                    level:1,
                    text:"示例-5层2",
                    id:12,
                },
                ]
            },
            {
                level:1,
                text:"示例-4层2",
                id:12,
            },
            ]
        },
        {
            level:1,
            text:"示例-3层2",
            id:12,
            nodes:[
            {
                level:1,
                text:"示例-4层1",
                id:12,
                nodes:[
                {
                    level:1,
                    text:"示例-5层1",
                    id:12,
                },
                {
                    level:1,
                    text:"示例-5层2",
                    id:12,
                },
                ]
            },
            {
                level:1,
                text:"示例-4层2",
                id:12,
            },
            ]
        },
        {
            level:1,
            text:"示例-3层3",
            id:12,
        },

        ]
    },
    {
        level:1,
        text:"示例-sub2",
        id:12,
        nodes:[
        {
            level:1,
            text:"示例-sub2-sub",
            id:12,
        },
        {
            level:1,
            text:"示例-sub2-sub",
            id:12,
        },
        {
            level:1,
            text:"示例-sub2-sub",
            id:12,
        },

        ]
    },
    {
        level:1,
        text:"示例-sub3",
        id:12,
        nodes:[
        {
            level:1,
            text:"示例-sub3-sub",
            id:12,
        },
        {
            level:1,
            text:"示例-sub3-sub",
            id:12,
        },
        {
            level:1,
            text:"示例-sub3-sub",
            id:12,
        },

        ]
    },
    ]
},
{
    level:0,
    text:'运维管理',
    id:2,
    nodes:[
    {
        level:1,
        text:"运维管理-sub1",
        id:21,
        nodes:[
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:22,
        },

        ]
    },
    {
        level:1,
        text:"运维管理-sub2",
        id:22,
        nodes:[
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:22,
        },

        ]
    },
    {
        level:1,
        text:"运维管理-sub3",
        id:22,
        nodes:[
        {
            level:1,
            text:"运维管理-sub3-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub3-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub3-sub",
            id:22,
        },

        ]
    },
    {
        level:1,
        text:"运维管理-sub4",
        id:22,
        nodes:[
        {
            level:1,
            text:"运维管理-sub4-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub4-sub",
            id:22,
        },
        {
            level:1,
            text:"运维管理-sub4-sub",
            id:22,
        },

        ]
    },
    ]
},
{
    level:0,
    text:'智慧食堂',
    id:3,
    nodes:[
    {
        level:1,
        text:"智慧食堂-sub1",
        id:31,
        nodes:[
        {
            level:1,
            text:"智慧食堂-sub2-sub",
            id:32,
        },
        {
            level:1,
            text:"智慧食堂-sub2-sub",
            id:32,
        },
        {
            level:1,
            text:"智慧食堂-sub2-sub",
            id:32,
        },

        ]
    },
    {
        level:1,
        text:"智慧食堂-sub2",
        id:32,
    },
    ]
},
{
    level:0,
    text:'APP管理',
    id:4,
    nodes:[
    {
        level:1,
        text:"APP管理-sub1",
        id:41,
        nodes:[
        {
            level:1,
            text:"APP管理-sub2-sub",
            id:42,
        },
        {
            level:1,
            text:"APP管理-sub2-sub",
            id:42,
        },
        {
            level:1,
            text:"APP管理-sub2-sub",
            id:42,
        },

        ]
    },
    {
        level:1,
        text:"APP管理-sub2",
        id:42,
    },
    ]
},
]