// data
var data = [
{
    level:0,
    text:'示例管理',
    id:1,
    nodes:[
    {
        level:1,
        text:"示例-2层",
        id:11,
        icon:"",
        nodes:[
        {
            level:1,
            text:"dome文档",
            id:111,
            href:"#dome-Doc",
        },
        {
            level:1,
            text:"container-1.html",
            id:112,
            href:"#container-1",
        },
        {
            level:1,
            text:"container-2.html",
            id:113,
            href:"#container-2",
        },
        {
            level:1,
            text:"子集4",
            id:114,
            href:"#container-2",
            nodes:[
                {
                    level:2,
                    text:"子集4-1",
                    id:1141,
                },
                {
                    level:2,
                    text:"子集4-2",
                    id:1142,
                },
            ]
        },
        ]
    },
    {
        level:1,
        text:"示例-sub2",
        id:12,
        nodes:[
        {
            level:1,
            text:"示例-sub2-sub",
            id:121,
        },
        {
            level:1,
            text:"示例-sub2-sub",
            id:122,
        },
        {
            level:1,
            text:"示例-sub2-sub",
            id:123,
        },

        ]
    },
    {
        level:1,
        text:"示例-sub3",
        id:13,
        nodes:[
        {
            level:1,
            text:"示例-sub3-sub",
            id:131,
        },
        {
            level:1,
            text:"示例-sub3-sub",
            id:132,
        },
        {
            level:1,
            text:"示例-sub3-sub",
            id:133,
        },

        ]
    },
    ]
},
{
    level:0,
    text:'运维管理',
    id:2,
    nodes:[
    {
        level:1,
        text:"运维管理-sub1",
        id:21,
        nodes:[
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:211,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:212,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:213,
        },

        ]
    },
    {
        level:1,
        text:"运维管理-sub2",
        id:22,
        nodes:[
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:221,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:222,
        },
        {
            level:1,
            text:"运维管理-sub2-sub",
            id:223,
        },

        ]
    },
    {
        level:1,
        text:"运维管理-sub3",
        id:23,
        nodes:[
        {
            level:1,
            text:"运维管理-sub3-sub",
            id:231,
        },
        {
            level:1,
            text:"运维管理-sub3-sub",
            id:232,
        },
        {
            level:1,
            text:"运维管理-sub3-sub",
            id:233,
        },

        ]
    },
    {
        level:1,
        text:"运维管理-sub4",
        id:24,
        nodes:[
        {
            level:1,
            text:"运维管理-sub4-sub",
            id:241,
        },
        {
            level:1,
            text:"运维管理-sub4-sub",
            id:242,
        },
        {
            level:1,
            text:"运维管理-sub4-sub",
            id:243,
        },

        ]
    },
    ]
},
{
    level:0,
    text:'智慧食堂',
    id:3,
    nodes:[
    {
        level:1,
        text:"智慧食堂-sub1",
        id:31,
        nodes:[
        {
            level:1,
            text:"智慧食堂-sub2-sub",
            id:32,
        },
        {
            level:1,
            text:"智慧食堂-sub2-sub",
            id:32,
        },
        {
            level:1,
            text:"智慧食堂-sub2-sub",
            id:32,
        },

        ]
    },
    {
        level:1,
        text:"智慧食堂-sub2",
        id:32,
    },
    ]
},
{
    level:0,
    text:'APP管理',
    id:4,
    nodes:[
    {
        level:1,
        text:"APP管理-sub1",
        id:41,
        nodes:[
        {
            level:1,
            text:"APP管理-sub2-sub",
            id:42,
        },
        {
            level:1,
            text:"APP管理-sub2-sub",
            id:42,
        },
        {
            level:1,
            text:"APP管理-sub2-sub",
            id:42,
        },

        ]
    },
    {
        level:1,
        text:"APP管理-sub2",
        id:42,
    },
    ]
},
]

// var objs = {
//     level:1,
//     text:"示例-2层",
//     id:11,
//     icon:"",
//     href:"/index.html",
// }
// objs["nodes"] = [];
// objs["nodes"].append(objs)